"""Spec 007 RF-1, RF-2: every dependency pinned, within its range and with hashes (plan-D6).

Reads the files only: no network. The lockfiles are generated by
`scripts/lock.sh` (Linux, Python 3.11) and never edited by hand.
"""

import re
import tomllib
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).parents[2]
PROD_LOCK = ROOT / "requirements.lock"
DEV_LOCK = ROOT / "requirements-dev.lock"

# `name==version \` followed by its `--hash=sha256:…` lines (pip-compile's format).
PINNED = re.compile(r"^([A-Za-z0-9._-]+)==(\S+)((?:\s*\\\s*--hash=sha256:[0-9a-f]{64})+)", re.M)


def project() -> dict:
    return tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]


def requirements(*, dev: bool) -> list[Requirement]:
    declared = project()["dependencies"]
    if dev:
        declared = declared + project()["optional-dependencies"]["dev"]
    return [Requirement(spec) for spec in declared]


def pinned(lock: Path) -> dict[str, tuple[str, str]]:
    """canonical name -> (version, hashes block) of every pin in `lock`."""
    text = lock.read_text(encoding="utf-8")
    return {canonicalize_name(m[1]): (m[2], m[3]) for m in PINNED.finditer(text)}


@pytest.mark.parametrize(
    ("lock", "dev"), [(PROD_LOCK, False), (DEV_LOCK, True)], ids=["prod", "dev"]
)
def test_every_direct_dependency_is_pinned_in_range_with_hashes(lock: Path, dev: bool) -> None:
    pins = pinned(lock)

    for requirement in requirements(dev=dev):
        name = canonicalize_name(requirement.name)
        assert name in pins, f"{name} missing from {lock.name}: run scripts/lock.sh"
        version, hashes = pins[name]
        assert requirement.specifier.contains(version), f"{name}=={version} out of range"
        assert "--hash=sha256:" in hashes


def test_the_production_lock_has_no_dev_tools() -> None:
    prod = pinned(PROD_LOCK)
    production = {canonicalize_name(r.name) for r in requirements(dev=False)}
    dev_only = {canonicalize_name(r.name) for r in requirements(dev=True)} - production

    assert dev_only, "the dev extra should add something"
    assert not dev_only & prod.keys()


@pytest.mark.parametrize("lock", [PROD_LOCK, DEV_LOCK], ids=["prod", "dev"])
def test_every_line_of_a_lock_is_pinned_with_a_hash(lock: Path) -> None:
    # Transitive dependencies too: `pip install --require-hashes` needs them all.
    text = lock.read_text(encoding="utf-8")
    entries = [line for line in text.splitlines() if line and line[0].isalnum()]

    assert entries
    assert len(entries) == len(pinned(lock))
